
# 项目相关配置
fuce:
  #名称
  name: Fc
  #版本
  version: 1.0
  #版权年份
  copyrightYear: 2018
  #头像上传路径
  profile: D:/profile/
  #地址是否放入项目static目录，如果未Y 放入static。 profile配置失效
  isstatic: Y
  #开启存放静态文件夹后目录
  isroot_dir: static/images_upload/
  #邮件功能
  #邮箱发送smtp
  email_smtp: smtp.sina.com
  #邮箱发送端口
  email_port: 465
  #发送邮箱登录账号
  email_account: 1131095930@qq.com
  #发送邮箱登录密码
  email_password: xy1131095930.
#tomcat config
server :
  port : 8082
  ##项目名字配置
  #servlet :
  #  context-path : /demo
  tomcat :
    max-threads : 128
    min-spare-threads : 5
    uri-encoding : UTF-8
    #shiro 报错修改的地方
    max-connections: 200000
    max-http-post-size: 9000000
spring :
#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategy
#    show-sql: true
 # 集成rabbitmq------------------------
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 60000ms
    # 支持发布确认
    publisher-confirms: true
    # 支持发布返回
    publisher-returns: true
    cache:
      channel:
        size: 1
  # Thread------------------------
    task:
      execution:
        pool:
          core-size: 4
          max-size: 8
          keep-alive: 60s
          queue-capacity: 20
  # Redis------------------------
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 10
        max-wait: 3
    lettuce:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
  # 环境 dev|test|prod
  profiles :
    active : dev
  servlet:
    multipart:
      max-request-size: 100MB
      maxFileSize : 10MB
        #shiro 报错修改的地方
    max-connections: 200000
    max-http-post-size: 9000000
  mvc:   #静态文件
    static-path-pattern : /static/**
  thymeleaf:
    model: HTML5
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


# 配置mybatisPlus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.myIsoland.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: default
      table-prefix: t_
      capital-mode: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#  config-location: classpath:/mapper/mybatis-config.xml